apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
spec: 
   initContainers:
     - name: init-co 
       image: alpine
       command:[ "sh", "-c", "echo '<h1> this is my app data </h1>' >> /usr/share/nginx/html/index.html"] 
       volumemount:
